FROM node:12-alpine

WORKDIR /usr/webapp/frontend

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

ARG REACT_APP_ENV
ARG REACT_APP_YAHOO_CLIENT_ID
ARG REACT_APP_YAHOO_OAUTH_REDIRECT_URL
ARG REACT_APP_ENABLE_BATTLEGROUND
ARG REACT_APP_SENTRY_DSN
ENV REACT_APP_ENV ${REACT_APP_ENV}
ENV REACT_APP_YAHOO_CLIENT_ID ${REACT_APP_YAHOO_CLIENT_ID}
ENV REACT_APP_YAHOO_OAUTH_REDIRECT_URL ${REACT_APP_YAHOO_OAUTH_REDIRECT_URL}
ENV REACT_APP_ENABLE_BATTLEGROUND ${REACT_APP_ENABLE_BATTLEGROUND}
ENV REACT_APP_SENTRY_DSN ${REACT_APP_SENTRY_DSN}
CMD ["yarn", "build"]
