const contest =
  {
    "createdAt": "2021-06-01T19:48:00.568Z",
    "updatedAt": "2021-06-01T19:48:00.568Z",
    "id": 1,
    "entryAmount": "20",
    "creatorPlayerProjFantasyPoints": "0",
    "claimerPlayerProjFantasyPoints": "0",
    "creatorPlayerCover": "15.454545453",
    "claimerPlayerCover": "15.454545453",
    "creatorPlayerWinBonus": "2.727272727",
    "claimerPlayerWinBonus": "2.727272727",
    "creatorPlayerSpread": "0",
    "claimerPlayerSpread": "0",
    "creatorPlayerMaxWin": "18.18181818",
    "claimerPlayerMaxWin": "18.18181818",
    "spreadValue": "17",
    "mlValue": "3",
    "type": "lobby",
    "status": "open",
    "ended": false,
    "endedAt": null,
    "winnerLabel": null,
    "creatorWinAmount": null,
    "claimerWinAmount": null,
    "topPropProfit": "0",
    "winnerId": null,
    "creatorId": 1,
    "claimerId": null,
    "creatorPlayerId": 4,
    "claimerPlayerId": 1,
    "spreadId": null,
    "creator": {
      "id": 1,
      "fullName": "John Doe",
      "username": "@john-doe",
      "email": "john.doe@gmail.com",
      "_customerToken": "cus_JapC5eSkUd9w3b",
      "_connectToken": "acct_1IxdYZQbE3b77COE",
      "accountConfirmedAt": "2021-06-01T18:50:28.515Z",
      "confirmAccountToken": null,
      "forgotPasswordToken": null,
      "forgotPasswordTokenExpiresIn": null,
      "socialId": null,
      "profileImage": null,
      "promo": null,
      "createdAt": "2021-06-01T18:50:28.518Z",
      "updatedAt": "2021-06-02T15:50:34.944Z"
    },
    "claimer": {
      "id": 1,
      "fullName": "John Doe",
      "username": "@john-doe",
      "email": "john.doe@gmail.com",
      "_customerToken": "cus_JapC5eSkUd9w3b",
      "_connectToken": "acct_1IxdYZQbE3b77COE",
      "accountConfirmedAt": "2021-06-01T18:50:28.515Z",
      "confirmAccountToken": null,
      "forgotPasswordToken": null,
      "forgotPasswordTokenExpiresIn": null,
      "socialId": null,
      "profileImage": null,
      "promo": null,
      "createdAt": "2021-06-01T18:50:28.518Z",
      "updatedAt": "2021-06-02T15:50:34.944Z"
    },
    "creatorPlayer": {
      "createdAt": "2021-06-01T18:49:10.791Z",
      "updatedAt": "2021-06-02T15:49:05.412Z",
      "id": 4,
      "remoteId": 19335,
      "firstName": "Antony",
      "lastName": "Auclair",
      "fullName": "Antony Auclair",
      "shortName": "A.Auclair",
      "status": "Active",
      "photoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19335.png",
      "photoUrlHiRes": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19335.png",
      "available": true,
      "position": "TE",
      "teamName": "HOU",
      "opponentName": null,
      "homeOrAway": null,
      "hasStarted": false,
      "isOver": false,
      "fantasyPoints": "0",
      "projectedFantasyPoints": "0",
      "teamId": 13
    },
    "claimerPlayer": {
      "createdAt": "2021-06-01T18:49:10.791Z",
      "updatedAt": "2021-06-02T15:49:05.362Z",
      "id": 1,
      "remoteId": 19304,
      "firstName": "Pharaoh",
      "lastName": "Brown",
      "fullName": "Pharaoh Brown",
      "shortName": "P.Brown",
      "status": "Active",
      "photoUrl": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19304.png",
      "photoUrlHiRes": "https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19304.png",
      "available": true,
      "position": "TE",
      "teamName": "HOU",
      "opponentName": null,
      "homeOrAway": null,
      "hasStarted": false,
      "isOver": false,
      "fantasyPoints": "0",
      "projectedFantasyPoints": "0",
      "teamId": 13
    }
};

export { contest };
